import { ArrowLeft } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";

export function TermsAndConditions() {
  const navigate = useNavigate();

  return (
    <main className="min-h-screen bg-background px-6 py-8 md:px-10">
      <div className="mx-auto flex w-full max-w-4xl flex-col gap-6">
        <div className="flex items-center justify-between gap-4">
          <Button variant="outline" onClick={() => navigate(-1)} className="gap-2">
            <ArrowLeft className="h-4 w-4" />
            Back
          </Button>
          <p className="text-xs text-muted-foreground">Last updated: March 2026</p>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Omnipresent Terms, Security and Privacy Notice</CardTitle>
            <CardDescription>
              Please read this document carefully before using the application.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <ScrollArea className="h-[70vh] rounded-lg border p-4" scrollbarGutter>
              <div className="space-y-6 text-sm leading-6 text-muted-foreground">
                <section className="space-y-2">
                  <h2 className="text-base font-semibold text-foreground">1. Scope</h2>
                  <p>
                    Omnipresent allows a mobile client on your local network to send input events
                    (cursor movement, clicks, scroll, and gesture actions) to this desktop app.
                    By using this software, you agree to these terms.
                  </p>
                </section>

                <section className="space-y-2">
                  <h2 className="text-base font-semibold text-foreground">
                    2. Core security model (technical summary)
                  </h2>
                  <p>
                    The core service uses UDP transport and a PIN-based token (`auth_token`) for
                    packet validation. Input messages are encoded with protobuf and include a
                    `sequence_number` to reduce replay and duplicate processing.
                  </p>
                  <p>
                    Pairing is QR-only. There is no discovery broadcast feature. Connection setup
                    depends on the QR payload generated by the desktop app, which may contain local
                    IP, listening port, and token.
                  </p>
                </section>

                <section className="space-y-2">
                  <h2 className="text-base font-semibold text-foreground">
                    3. Authentication and local secrets
                  </h2>
                  <p>
                    A numeric token is generated and stored locally on your machine in a plain text
                    file for reuse between runs. Anyone with local file-system access to that file
                    may potentially recover the token.
                  </p>
                  <p>
                    You are responsible for your endpoint hardening, user account protection,
                    filesystem permissions, and periodic token reset when needed.
                  </p>
                </section>

                <section className="space-y-2">
                  <h2 className="text-base font-semibold text-foreground">
                    4. Network and privacy behavior
                  </h2>
                  <p>
                    The desktop app can query and display current WiFi information (SSID/interface)
                    for diagnostics and user visibility. Pairing data may include local IP, port,
                    and token in QR or URI format.
                  </p>
                  <p>
                    Network traffic is intended for local-network operation. You must not expose the
                    service to untrusted networks without additional protections (firewall
                    restrictions, VPN, segmentation, or equivalent controls).
                  </p>
                </section>

                <section className="space-y-2">
                  <h2 className="text-base font-semibold text-foreground">
                    5. Input control and system impact
                  </h2>
                  <p>
                    This software can trigger native OS input actions using platform-specific APIs.
                    If misused, compromised, or configured insecurely, it can alter normal system
                    behavior, execute unintended interactions, or disrupt workflows.
                  </p>
                </section>

                <section className="space-y-2">
                  <h2 className="text-base font-semibold text-foreground">
                    6. User responsibilities
                  </h2>
                  <p>You agree to:</p>
                  <ul className="list-disc space-y-1 pl-5">
                    <li>Use the software only on devices and networks you are authorized to use.</li>
                    <li>Keep your local environment and OS security controls updated.</li>
                    <li>Avoid sharing pairing tokens, QR codes, or connection URIs.</li>
                    <li>
                      Stop the service when not in use, especially on shared or less-trusted
                      networks.
                    </li>
                    <li>
                      Ensure compliance with all applicable laws, organizational policies, and
                      security requirements.
                    </li>
                  </ul>
                </section>

                <section className="space-y-2">
                  <h2 className="text-base font-semibold text-foreground">
                    7. Important disclaimer of liability
                  </h2>
                  <p className="font-medium text-foreground">
                    We are not responsible for misuse, abuse, unauthorized access, system
                    compromise, data loss, service interruption, or any direct/indirect damages
                    resulting from the use or inability to use this software.
                  </p>
                  <p>
                    This includes, without limitation, vulnerabilities introduced by your
                    environment, insecure deployments, weak endpoint controls, exposure to hostile
                    networks, third-party attacks, or user/operator error.
                  </p>
                </section>

                <section className="space-y-2">
                  <h2 className="text-base font-semibold text-foreground">
                    8. No warranty
                  </h2>
                  <p>
                    The software is provided "as is" and "as available" without warranties of any
                    kind, express or implied, including merchantability, fitness for a particular
                    purpose, and non-infringement.
                  </p>
                </section>

                <section className="space-y-2">
                  <h2 className="text-base font-semibold text-foreground">
                    9. Acceptance
                  </h2>
                  <p>
                    By checking acceptance and continuing to use Omnipresent, you confirm that you
                    understand and agree to these terms, security considerations, and risk
                    allocation.
                  </p>
                </section>
              </div>
            </ScrollArea>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}
